name: "Lint Markdown"

on:
  push:
    paths-ignore:
    - .*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - Makefile
  pull_request:
    paths-ignore:
    - .*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - Makefile

jobs:
  lint-changelog:
    name: Lint Markdown
    uses: avto-dev/markdown-lint@v1.5.0
    with:
      config: '.github/workflows/markdownlint.json'
      args: 'draft-*.md'
