name: "Update Editor's Copy"

on:
  push:
    paths-ignore:
    - .*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - Makefile
  pull_request:
    paths-ignore:
    - .*
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - Makefile

jobs:
  lint-changelog:
    name: Lint I-D
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint I-D file
      uses: docker://avtodev/markdown-lint:v1
      with:
        # rules: '.markdownlint.json'
        args: 'draft-*.md'
